[General]
EnableNetworkConfiguration=true
UseDefaultInterface=true

[Network]
# Use 'none' to let iwd write directly to /etc/resolv.conf
NameResolvingService=none
EnableIPv6=false

[Settings]
AutoConnect=true
